### ISSUE TITLE
Etc/UTC not acceptable

### ISSUE THREAD

**Issue by hmaesta** [rallisf1/svelte-countdown#2]
Etc/UTC is on database:

https://github.com/rallisf1/svelte-countdown/blob/4d0db6bd98115707d2208c616696e91ae0b6347c/src/database.js#L1412-L1414

... but when using `zone="Etc/UTC"`:

> [svelte-countdown] Timezone not found in database. Please use a canonical timezone from (...)
> [svelte-countdown] Intl API not supported by browser, cannot calculate timezone difference!

**Comment by xpluscal** [comment]
Same for America/New_York. Is that an issue with the plugin?

**Comment by vgb0332** [comment]
Looked through the src and found on

[svelte-countdown/srx/Coundtdown.svelte

> ``](https://github.com/rallisf1/svelte-countdown/blob/378f57eb6b1c34bff8aa2f5f99d8b7b5a2848e77/src/Countdown.svelte#L30-L36)

during destruction process on remoteTZ and localTZ variables, notice the first letter is NOT capitalized while in database.js it is.
Capitalizing the first letter solves the issue, but you will have to do it inside node_modules.

Hope this is fixed and updated soon @rallisf1
