### ISSUE TITLE
Wrong readme

### ISSUE THREAD

**Issue by hazg** [rallisf1/svelte-countdown#3]
import Countdown from 'svelte-countdown/src/index.js'; 
ok

import Countdown from 'svelte-countdown';
Module not found: Error: Can't resolve 'svelte-countdown' in ***

**Comment by alestry-perez** [comment]
I created a pull request with this fix, hopefully, it gets accepted soon!

**Comment by rallisf1** [comment]
> I created a pull request with this fix, hopefully, it gets accepted soon!

thanks
